alias ls='ls --color'
alias ll='ls -al'
alias grep='egrep --color'
alias rm='rm -i'
alias mv='mv -i'
alias prettyjson='python -m json.tool'
alias virtualenv='virtualenv -p python3'
alias nslookup='getent hosts'
